### ISSUE TITLE
Feature: Offline mode

### ISSUE THREAD

**Issue by jtemplet** [finnp/create-module#11]
It would be nice to have --offline flag so that (a) you can use this tool when you don't have access to the internet and (b) do not want to use github (maybe you use gitlab or bitbucket)

**Comment by finnp** [comment]
Sounds great! I just thought maybe we can decouple the workflow a bit by creating a module like `github-repo`, which would do the following steps for github:
* create GitHub repository with module name
* add GitHub repository to package.json
* git remote add origin <githubrepo>
* git push origin master

Then we could change the workflow to first do all the offline capable steps and then optionally followed by `create-module-repo`.

So `create-module` would be the same as doing `create-module --offline && github-repo`

**Comment by jtemplet** [comment]
So you want me to pull the github stuff out all together?

**Comment by klaemo** [comment]
If we want to get really fancy, those `create-repo` packages could be something like plugins, so people could provide plugins for other backends. :)
That enables us to have `create-module --gitlab` or `create-module --bitbucket`.

**Comment by finnp** [comment]
@jtemplet That's not exactly what we want. This project assumes that you haven't initialized a git repository yet. Creating a PR there would be one way to go, but I guess it would be simpler just to create a new one for this use case.

@klaemo Yes that sounds great. If there is anyone using those things :smile:

**Comment by jtemplet** [comment]
@finnp I'm unclear as to what you're suggesting/recommending for this feature.

Are you agreeing to the need of the --offline mode? I apologize for my confusion.

@klaemo That sounds really cool, but also, a lot of work. I'm just trying to scratch my own itch right now. ;)

**Comment by jtemplet** [comment]
@finnp If I understand what you're suggesting, we have an --offline flag and what that will skip these steps:
* create GitHub repository with module name
* add GitHub repository to package.json
* git remote add origin
* git push origin master

And then we create another module to do the above steps. 

Does that sounds about right?

**Comment by finnp** [comment]
Yes, that's exactly the idea. Do you want to take a stab at this?
