### ISSUE TITLE
.gitignore node_modules

### ISSUE THREAD

**Issue by klaemo** [finnp/create-module#6]
What do you think about adding a `echo "node_modules"  > .gitignore` step?

**Comment by finnp** [comment]
Yes, I think that could be useful. I also wondered if I should use the GitHub [node template](https://github.com/github/gitignore/blob/master/Node.gitignore). But I think that's a bit verboose, because I don't usually use most of this. `node_modules` makes sense though.

**Comment by finnp** [comment]
Added this in `1.2.0`

**Comment by klaemo** [comment]
\o/ good refactoring as well. Would've been my next suggestion ;)

**Comment by finnp** [comment]
Haha, thanks. It really started to be a bit of a callback hell :fire::fire:
